# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: gh:linkml/linkml-project-copier
add_example: false
copyright_year: '2024'
email: scott.christley@utsouthwestern.edu
full_name: Scott Christley
gh_action_docs_preview: true
gh_action_pypi: true
github_org: airr-knowledge
license: GPL-3.0-only
project_description: AK Schema
project_name: ak-schema
project_slug: ak_schema

