# Configuration of generators (defaults illustrated)
---
includes:
  owl:
  jsonld:
  jsonschema:
  python:
  sqlddl:

generator_args:
  owl:
    mergeimports: true
    metaclasses: true
    type_objects: true
    # throws 'Cannot handle metadata profile: rdfs'
    # metadata_profile: rdfs
  jsonld:
    mergeimports: true
  jsonschema:
    mergeimports: true
  python:
    mergeimports: true
  sqlddl:
    mergeimports: true

...
