AIRR_SCHEMA_DIR=src/ak_schema/schema/airr
SCRIPT_DIR=src/scripts/airr2akc

airr: repertoire rearrangement clone cell receptor germline

repertoire: Study Subject Diagnosis Genotype MHCGenotype Sample PCRTarget CellProcessing NucleicAcidProcessing SequencingRun SequencingData DataProcessing Repertoire

rearrangement: Rearrangement

clone: Clone

cell: Cell Expression Reactivity

receptor: Receptor

germline: GermlineSet AlleleDescription SequenceDelineationV RearrangedSequence UnrearrangedSequence

Study:
	python $(SCRIPT_DIR)/airr2akc.py Study $(AIRR_SCHEMA_DIR)/ak_Study.yaml
Subject:
	python $(SCRIPT_DIR)/airr2akc.py Subject $(AIRR_SCHEMA_DIR)/ak_Subject.yaml
Diagnosis:
	python $(SCRIPT_DIR)/airr2akc.py Diagnosis $(AIRR_SCHEMA_DIR)/ak_Diagnosis.yaml
Genotype:
	python $(SCRIPT_DIR)/airr2akc.py Genotype $(AIRR_SCHEMA_DIR)/ak_Genotype.yaml
MHCGenotype:
	python $(SCRIPT_DIR)/airr2akc.py MHCGenotype $(AIRR_SCHEMA_DIR)/ak_MHCGenotype.yaml
Sample:
	python $(SCRIPT_DIR)/airr2akc.py Sample $(AIRR_SCHEMA_DIR)/ak_Sample.yaml
PCRTarget:
	python $(SCRIPT_DIR)/airr2akc.py PCRTarget $(AIRR_SCHEMA_DIR)/ak_PCRTarget.yaml
CellProcessing:
	python $(SCRIPT_DIR)/airr2akc.py CellProcessing $(AIRR_SCHEMA_DIR)/ak_CellProcessing.yaml
NucleicAcidProcessing:
	python $(SCRIPT_DIR)/airr2akc.py NucleicAcidProcessing $(AIRR_SCHEMA_DIR)/ak_NucleicAcidProcessing.yaml
SequencingRun:
	python $(SCRIPT_DIR)/airr2akc.py SequencingRun $(AIRR_SCHEMA_DIR)/ak_SequencingRun.yaml
SequencingData:
	python $(SCRIPT_DIR)/airr2akc.py SequencingData $(AIRR_SCHEMA_DIR)/ak_SequencingData.yaml
DataProcessing:
	python $(SCRIPT_DIR)/airr2akc.py DataProcessing $(AIRR_SCHEMA_DIR)/ak_DataProcessing.yaml
Repertoire:
	python $(SCRIPT_DIR)/airr2akc.py Repertoire $(AIRR_SCHEMA_DIR)/ak_Repertoire.yaml
#
# Rearrangement rules
# 
Rearrangement:
	python $(SCRIPT_DIR)/airr2akc.py Rearrangement $(AIRR_SCHEMA_DIR)/ak_Rearrangement.yaml
#
# Clone rules
# 
Clone:
	python $(SCRIPT_DIR)/airr2akc.py Clone $(AIRR_SCHEMA_DIR)/ak_Clone.yaml
#
# Cell rules
# 
Cell:
	python $(SCRIPT_DIR)/airr2akc.py Cell $(AIRR_SCHEMA_DIR)/ak_Cell.yaml
Expression:
	python $(SCRIPT_DIR)/airr2akc.py CellExpression $(AIRR_SCHEMA_DIR)/ak_CellExpression.yaml
Reactivity:
	python $(SCRIPT_DIR)/airr2akc.py ReceptorReactivity $(AIRR_SCHEMA_DIR)/ak_ReceptorReactivity.yaml
#
# Rearrangement rules
# 
Receptor:
	python $(SCRIPT_DIR)/airr2akc.py Receptor $(AIRR_SCHEMA_DIR)/ak_Receptor.yaml
#
# Germline rules
# 
GermlineSet:
	python $(SCRIPT_DIR)/airr2akc.py GermlineSet $(AIRR_SCHEMA_DIR)/ak_GermlineSet.yaml
AlleleDescription:
	python $(SCRIPT_DIR)/airr2akc.py AlleleDescription $(AIRR_SCHEMA_DIR)/ak_AlleleDescription.yaml
RearrangedSequence:
	python $(SCRIPT_DIR)/airr2akc.py RearrangedSequence $(AIRR_SCHEMA_DIR)/ak_RearrangedSequence.yaml
UnrearrangedSequence:
	python $(SCRIPT_DIR)/airr2akc.py UnrearrangedSequence $(AIRR_SCHEMA_DIR)/ak_UnrearrangedSequence.yaml
SequenceDelineationV:
	python $(SCRIPT_DIR)/airr2akc.py SequenceDelineationV $(AIRR_SCHEMA_DIR)/ak_SequenceDelineationV.yaml

