all: PRJNA248411 PRJNA248475 PRJNA300878 PRJNA280743 PRJNA381394 PRJNA509910 PRJNA680539 PRJNA724733 PRJNA472381 PRJNA608742 IR-T1D-000003

PRJNA248411:
	bash akc-convert-study.sh ipa1.ireceptor.org PRJNA248411 test
PRJNA248475:
	bash akc-convert-study.sh vdjserver.org PRJNA248475 test
PRJNA300878:
	bash akc-convert-study.sh vdjserver.org PRJNA300878  test
PRJNA280743:
	bash akc-convert-study.sh ipa1.ireceptor.org PRJNA280743 test
PRJNA381394:
	bash akc-convert-study.sh ipa5.ireceptor.org PRJNA381394 test
PRJNA509910:
	bash akc-convert-study.sh ipa6.ireceptor.org PRJNA509910 test
PRJNA680539:
	bash akc-convert-study.sh vdjserver.org PRJNA680539 test
PRJNA724733:
	bash akc-convert-study.sh vdjserver.org PRJNA724733 test
PRJNA472381:
	bash akc-convert-study.sh vdjserver.org PRJNA472381 test
PRJNA608742:
	bash akc-convert-study.sh vdjserver.org PRJNA608742 test
IR-T1D-000003:
	bash akc-convert-study.sh t1d-2.ireceptor.org IR-T1D-000003 test
